dataset_name: ccdv/arxiv-summarization
train_size: 16000
val_size: 2000
test_size: 2000

max_input_length: 1024
max_output_length: 128

model_name: allenai/led-base-16384

lora_r: 8
lora_alpha: 32
lora_dropout: 0.1

batch_size: 1
grad_accumulation: 2
epochs: 3

num_beams: 4
length_penalty: 2.0
